networks:
  default:
    name: xoxxox_netmid
    external: true
services:
  xoxxox_sensim:
    image: xoxxox_envweb:001
    container_name: xoxxox_sensim
    volumes:
    - ../../../export:/opt/common
    env_file:
    - ./envdir.txt
    ports:
    - 10401:80
    command: "python /opt/common/bin/xoxxox/srvsen.py --engine xoxxox/engine_sensim"
